# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2dda86b644cd727767ce3d942a28593d61889ef6425cf215000b8ba79347a115590794f27d67884a15120a658a8c19f9c1c2737ce7351fd5c63985a89f77da0a

test:
  secret_key_base: 4d0f7506b013583850166f1814216eeb7347f1a9fea2258ece9efe2532e8d7e7b977284004cc71ee87970d991be2f1db668c988323c60932e3a31636d85c3f6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
